<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        // 创建 Promise 对象 Promise 不是成功就是出错
        const p = new Promise((resolve, reject) => {
            setTimeout(function () {
                resolve('用户数据');
                // reject('出错了');
            }, 1000)
        });
        //调用then方法，then方法返回的是一个 promise对象，对象的状态由回调函数的执行结果决定
        //1.如果回调函数返回的状态是一个 非promise类型的属性(字符串，数组等等)，状态为成功，返回值为对象的成功的值
        //由此可知，因为函数不写return的话，那么函数的默认返回值就是undefined,undefined为一个非promise值
        // 所以then的返回的状态就是成功
        //2.如果是一个 promise的对象，那么回调函数返回的状态由这个 promise对象的状态决定 此promise的状态为成功，那么 then的返回状态就是成功，反之同理
        // 3.抛出一个错误 状态为错误

        // 1. 调用 then 方法 then 方法返回的结果是 Promise 对象 对象状态由回调函数的执行结果决定
        // 2. 如果回调函数返回的结不是 Promise 类型的属性 状态就为成功 返回值为对象成功的值
        const result = p.then(value => {
            console.log(value);
            // 1. 非 Promise 类型的属性 成功状态 返回值为对象的结果
            // return '123'; // 成功 123

            // 2. 是 Promise 对象 状态就由内部 Promise 状态决定
            return new Promise((resolve, reject) => {
                // resolve('ok');
                reject('error');
            })
        }, reason => {
            console.log(reason);
        });

        // 链式调用 then 一个跟着一个异步任务 链式调用来改变回调地狱现象 then 方法里面最多两个回调函数 第一个是成功 第二个是失败
        p.then(value => {
            console.log(value);
        }).then(value => {
            console.log(value);
        })
        console.log(result);
    </script>
</body>

</html>